version: "3.9"
services:
  postgres:
    image: postgres:13.3
    environment:
      POSTGRES_DB: "todo"
      POSTGRES_USER: "postgress"
      POSTGRES_PASSWORD: "postgress"
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    container_name: backend
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    command: ["sh", "-c", "sleep 10 && npm start"]
    env_file:
      - .env

  frontend:
    build:
      context: frontend
    container_name: frontend
    working_dir: /usr/src/app
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "3000:80"
    depends_on:
      - backend
