import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Home from "./page";
import { Footer } from "@/components/TheFooter";
import { Header } from "@/components/TheHeader";
import { TodoPage } from "@/components/TodoPage";
import { Container } from "@mui/material";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Note",
  description: "Generated by create next app",
};

export default function RootLayout() {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Container
          sx={{
            minHeight: "100vh",
            display: "flex",
            flexDirection: "column",
            justifyContent: "space-between",
          }}
        >
          <Header />
          <TodoPage />
          <Footer />
        </Container>
      </body>
    </html>
  );
}
